# Generated by Django 2.2.9 on 2021-09-08 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getecoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_hora_atencion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_solicitud',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_final_atencion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='respuesta',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(max_length=150),
        ),
    ]
