# Generated by Django 2.2.9 on 2021-09-08 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getecoapp', '0002_auto_20210908_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_hora_atencion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='hora_final_atencion',
            field=models.DateField(),
        ),
    ]
