# Generated by Django 2.2.9 on 2021-09-08 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getecoapp', '0003_auto_20210908_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getecoapp.Ciudad', verbose_name='ciudad_empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getecoapp.Empresa', verbose_name='empresa_empleado'),
        ),
    ]
